### PR TITLE
Added rudimentary code editor

### PR DESCRIPTION
**Pull request by ThunderousEcho**
Known shortcomings:

- No ability to edit or delete existing files (should this be triggered from the modules tab or do we want some psuedo-file-explorer?)
- Editor opens at a very small size (and I don't know why, the settings are the same as for the modules window)
- No warning about losing unsaved code when closing
- Unsaved code is lost when the Esc menu is opened
- No syntax highlighting

Addresses #13

### CODE REVIEW

**Comment by ThunderousEcho** [comment]
On second thought- I've made this a draft until some of these shortcomings are addressed. @untoldwind please respond with guidance on the first two shortcomings.

**Comment by untoldwind** [comment]
So cool that you are working on this:

## Editing existing files

I just added source-file information to `IKontrolModule`.
So if you filter
```
Mainframe.Instance.LastRegistry?.modules.Values
```
for everthing with `!IsBuiltin` (or just `SourceFile != null`) you should get a list of editable file names.

## Window size

There is probably something fishy with the `initialMinWidth/Height` parameter, try to give the initial Rect
```
new Rect(Screen.width - 750, Screen.height - 600, 0, 0)
```
as width, height as well.

## ESC menu

The `hideAllWindows` flag is a good idea, I'm not sure how Unity deals with static fields in GameObjects though. Maybe that should be a flag in a shared singleton?

In general: I would say that a little warning header or footer with "Unsaved changes" would be enough for the start.

**Comment by untoldwind** [comment]
As for the syntax highlighting.

I was playing with this for a bit. You can set `richText` for a TextArea, but then the editing gets wonky. I found a trick in the unity forum to use two textareas above each other.

```
            GUIStyle sourceTextArea = new GUIStyle(Skins.ConsoleSkin.textArea);
            sourceTextArea.font = FontManager.Instance.GetSystemFontByNameAndSize(FontManager.DefaultConsoleFonts, 12, true);
            sourceTextArea.fontSize = 12;
            GUIStyle highlighter = new GUIStyle(sourceTextArea);
            highlighter.richText = true;
```

An then in the DrawGUI loop:

```
painText = GUILayout.TextArea(painText, sourceTextArea); // plainText has no rechtext attributes
Rect r = GUILayoutUtility.GetLastRect();
 
GUI.TextArea(r, AddHighlight(painText), highlighter); //AddHighlight adds some richtext attributes
```

Not sure how good this works in practice

**Comment by ThunderousEcho** [comment]
@untoldwind It seems like a lot of files from outside the to2Local folder are getting marked as Builtin: False. Is this intentional? Is it intended that users be able to edit these files?

**Comment by untoldwind** [comment]
Generally: All modules starting with `core::` or `ksp::` should be marked as `BuiltIn = true`, because they are implemented in C#. Everything else is implemented in the scripting language itself.

What I'm aiming for is something like this:
<PluginFolder>/to2 - shipped with the plugin itself, containing some examples and the `std::` modules, which serve as a sort of standard library for maneuvers and such.
<PluginFolder>/to2Local - all the scripts the individual user creates.

That said: The `std::` library is by no means finished or covers all the many cases. My hope is that over the time people will add to it or optimize certain parts.
So yes: Tweaking the std-library is intended as far as I am concerned ;)

**Pull request merged**
